name: spacewar
dependencies:
  sky: any
  flutter: any
  sky_tools: any
  vector_math: any
  benchmark_harness: any
dependency_overrides:
  flutter:
    path: ../../tools/git/flutter/packages/flutter
